name: Create Release with Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip repository contents
        run: |
          zip -r RedWolf.zip .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload zip file to release
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedWolf.zip
          asset_name: RedWolf.zip
          asset_content_type: application/zip

      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          hash-type: sha1
          file-name: hashes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes.txt
