name: Create Release with Zip File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip repository contents
        run: |
          zip -r RedWolf.zip . -x .git/\* -x .github/\*

      - name: Generate SHA-1
        run: |
          sha1sum RedWolf.zip > RedWolf.zip.sha1

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload zip file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedWolf.zip
          asset_name: RedWolf.zip
          asset_content_type: application/zip

      - name: Upload SHA-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./RedWolf.zip.sha1
          asset_name: RedWolf.zip.sha1
          asset_content_type: text/plain
